# Generated by Django 5.2.4 on 2025-08-22 02:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0004_processingtask_created_by_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingtask",
            name="task_type",
            field=models.CharField(max_length=100, verbose_name="任务类型"),
        ),
        migrations.AlterField(
            model_name="remotesensingimage",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "等待中"),
                    ("processing", "处理中"),
                    ("completed", "已完成"),
                    ("failed", "失败"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="处理状态",
            ),
        ),
    ]
