# Generated by Django 5.2.4 on 2025-08-26 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0005_alter_processingtask_task_type_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="ecologicalindex",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建用户",
            ),
        ),
        migrations.AlterField(
            model_name="processingtask",
            name="task_type",
            field=models.CharField(max_length=50, verbose_name="任务类型"),
        ),
        migrations.AlterField(
            model_name="remotesensingimage",
            name="processing_status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("processing", "处理中"),
                    ("completed", "已完成"),
                    ("failed", "处理失败"),
                    ("cancelled", "已取消"),
                ],
                default="pending",
                max_length=20,
                verbose_name="处理状态",
            ),
        ),
    ]
