# Generated by Django 5.2.4 on 2025-08-18 09:05

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="EcologicalIndex",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "index_type",
                    models.CharField(
                        choices=[
                            ("ndvi", "NDVI - 归一化植被指数"),
                            ("ndwi", "NDWI - 归一化水体指数"),
                            ("ndbi", "NDBI - 归一化建筑指数"),
                            ("ndsi", "NDSI - 归一化积雪指数"),
                            ("rsei", "RSEI - 遥感生态指数"),
                            ("wetness", "湿度指数"),
                            ("dryness", "干度指数"),
                            ("heat", "热度指数"),
                            ("greenness", "绿度指数"),
                        ],
                        max_length=20,
                        verbose_name="指数类型",
                    ),
                ),
                (
                    "result_file",
                    models.FileField(
                        upload_to="ecological_indices/", verbose_name="结果文件"
                    ),
                ),
                (
                    "visualization_file",
                    models.ImageField(
                        upload_to="visualizations/", verbose_name="可视化图片"
                    ),
                ),
                (
                    "min_value",
                    models.FloatField(blank=True, null=True, verbose_name="最小值"),
                ),
                (
                    "max_value",
                    models.FloatField(blank=True, null=True, verbose_name="最大值"),
                ),
                (
                    "mean_value",
                    models.FloatField(blank=True, null=True, verbose_name="平均值"),
                ),
                (
                    "std_value",
                    models.FloatField(blank=True, null=True, verbose_name="标准差"),
                ),
                (
                    "excellent_area",
                    models.FloatField(
                        blank=True, null=True, verbose_name="优秀面积(km²)"
                    ),
                ),
                (
                    "good_area",
                    models.FloatField(
                        blank=True, null=True, verbose_name="良好面积(km²)"
                    ),
                ),
                (
                    "moderate_area",
                    models.FloatField(
                        blank=True, null=True, verbose_name="中等面积(km²)"
                    ),
                ),
                (
                    "poor_area",
                    models.FloatField(
                        blank=True, null=True, verbose_name="较差面积(km²)"
                    ),
                ),
                (
                    "bad_area",
                    models.FloatField(
                        blank=True, null=True, verbose_name="差面积(km²)"
                    ),
                ),
                (
                    "processing_time",
                    models.FloatField(
                        blank=True, null=True, verbose_name="处理时间(秒)"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "生态指数",
                "verbose_name_plural": "生态指数",
                "db_table": "ecological_indices",
            },
        ),
        migrations.CreateModel(
            name="ProcessingTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("task_type", models.CharField(max_length=50, verbose_name="任务类型")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度百分比")),
                (
                    "current_step",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="当前步骤"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
            ],
            options={
                "verbose_name": "处理任务",
                "verbose_name_plural": "处理任务",
                "db_table": "processing_tasks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RemoteSensingImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="影像名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "image_type",
                    models.CharField(
                        choices=[
                            ("landsat8", "Landsat 8"),
                            ("landsat9", "Landsat 9"),
                            ("sentinel2", "Sentinel-2"),
                            ("custom", "自定义"),
                        ],
                        max_length=20,
                        verbose_name="影像类型",
                    ),
                ),
                (
                    "file_path",
                    models.FileField(
                        upload_to="remote_sensing/", verbose_name="影像文件"
                    ),
                ),
                (
                    "thumbnail",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="thumbnails/",
                        verbose_name="缩略图",
                    ),
                ),
                ("center_lat", models.FloatField(verbose_name="中心纬度")),
                ("center_lon", models.FloatField(verbose_name="中心经度")),
                ("acquisition_date", models.DateField(verbose_name="获取日期")),
                (
                    "processing_date",
                    models.DateTimeField(auto_now_add=True, verbose_name="处理时间"),
                ),
                (
                    "resolution",
                    models.FloatField(blank=True, null=True, verbose_name="分辨率(米)"),
                ),
                (
                    "bands_count",
                    models.IntegerField(blank=True, null=True, verbose_name="波段数"),
                ),
                (
                    "file_size",
                    models.BigIntegerField(
                        blank=True, null=True, verbose_name="文件大小(字节)"
                    ),
                ),
                (
                    "is_processed",
                    models.BooleanField(default=False, verbose_name="是否已处理"),
                ),
                (
                    "processing_status",
                    models.CharField(
                        default="pending", max_length=20, verbose_name="处理状态"
                    ),
                ),
            ],
            options={
                "verbose_name": "遥感影像",
                "verbose_name_plural": "遥感影像",
                "db_table": "remote_sensing_images",
                "ordering": ["-acquisition_date"],
            },
        ),
        migrations.CreateModel(
            name="RSEIResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "pc1_variance",
                    models.FloatField(verbose_name="第一主成分方差贡献率"),
                ),
                (
                    "pc2_variance",
                    models.FloatField(verbose_name="第二主成分方差贡献率"),
                ),
                (
                    "pc3_variance",
                    models.FloatField(verbose_name="第三主成分方差贡献率"),
                ),
                (
                    "pc4_variance",
                    models.FloatField(verbose_name="第四主成分方差贡献率"),
                ),
                ("greenness_weight", models.FloatField(verbose_name="绿度权重")),
                ("wetness_weight", models.FloatField(verbose_name="湿度权重")),
                ("dryness_weight", models.FloatField(verbose_name="干度权重")),
                ("heat_weight", models.FloatField(verbose_name="热度权重")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "RSEI结果",
                "verbose_name_plural": "RSEI结果",
                "db_table": "rsei_results",
            },
        ),
    ]
