# Generated by Django 5.2.4 on 2025-08-18 09:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("environment", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="remotesensingimage",
            name="uploaded_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="上传用户",
            ),
        ),
        migrations.AddField(
            model_name="processingtask",
            name="remote_sensing_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="environment.remotesensingimage",
                verbose_name="遥感影像",
            ),
        ),
        migrations.AddField(
            model_name="ecologicalindex",
            name="remote_sensing_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="environment.remotesensingimage",
                verbose_name="遥感影像",
            ),
        ),
        migrations.AddField(
            model_name="rseiresult",
            name="dryness",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rsei_dryness",
                to="environment.ecologicalindex",
                verbose_name="干度指数",
            ),
        ),
        migrations.AddField(
            model_name="rseiresult",
            name="greenness",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rsei_greenness",
                to="environment.ecologicalindex",
                verbose_name="绿度指数",
            ),
        ),
        migrations.AddField(
            model_name="rseiresult",
            name="heat",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rsei_heat",
                to="environment.ecologicalindex",
                verbose_name="热度指数",
            ),
        ),
        migrations.AddField(
            model_name="rseiresult",
            name="remote_sensing_image",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="environment.remotesensingimage",
                verbose_name="遥感影像",
            ),
        ),
        migrations.AddField(
            model_name="rseiresult",
            name="rsei_result",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rsei_final",
                to="environment.ecologicalindex",
                verbose_name="RSEI结果",
            ),
        ),
        migrations.AddField(
            model_name="rseiresult",
            name="wetness",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rsei_wetness",
                to="environment.ecologicalindex",
                verbose_name="湿度指数",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="ecologicalindex",
            unique_together={("remote_sensing_image", "index_type")},
        ),
    ]
