# Generated by Django 5.2.4 on 2025-08-22 01:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0003_alter_remotesensingimage_uploaded_by"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="processingtask",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="创建用户",
            ),
        ),
        migrations.AlterField(
            model_name="processingtask",
            name="task_type",
            field=models.CharField(
                choices=[
                    ("ecological_indices", "生态指数计算"),
                    ("rsei_calculation", "RSEI计算"),
                    ("land_use_analysis", "土地利用分析"),
                    ("custom", "自定义分析"),
                ],
                max_length=50,
                verbose_name="任务类型",
            ),
        ),
    ]
