# Generated by Django 5.2.4 on 2025-08-27 08:15

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0006_ecologicalindex_created_by_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CitizenFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("suggestion", "功能建议"),
                            ("bug", "问题报告"),
                            ("data_issue", "数据纠错"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="反馈类型",
                    ),
                ),
                ("title", models.CharField(max_length=80, verbose_name="标题")),
                ("content", models.TextField(verbose_name="详细描述")),
                (
                    "contact",
                    models.CharField(
                        blank=True, max_length=120, null=True, verbose_name="联系方式"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="提交时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="提交用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "民众意见反馈",
                "verbose_name_plural": "民众意见反馈",
                "db_table": "citizen_feedbacks",
                "ordering": ["-created_at"],
            },
        ),
    ]
