# Generated by Django 5.2.4 on 2025-09-04 07:16

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0007_citizenfeedback"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ClimateDataFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file",
                    models.FileField(upload_to="climate_data/", verbose_name="文件"),
                ),
                (
                    "file_type",
                    models.CharField(
                        choices=[("csv", "CSV"), ("xlsx", "Excel")],
                        max_length=10,
                        verbose_name="文件类型",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "已上传"),
                            ("processing", "处理中"),
                            ("completed", "完成"),
                            ("failed", "失败"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理完成时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "气候数据文件",
                "verbose_name_plural": "气候数据文件",
                "db_table": "climate_data_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClimateAnalysisResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "analysis_type",
                    models.CharField(
                        default="comprehensive", max_length=50, verbose_name="分析类型"
                    ),
                ),
                (
                    "temperature_avg",
                    models.FloatField(blank=True, null=True, verbose_name="平均温度"),
                ),
                (
                    "temperature_max",
                    models.FloatField(blank=True, null=True, verbose_name="最高温度"),
                ),
                (
                    "temperature_min",
                    models.FloatField(blank=True, null=True, verbose_name="最低温度"),
                ),
                (
                    "temperature_std",
                    models.FloatField(blank=True, null=True, verbose_name="温度标准差"),
                ),
                (
                    "precipitation_avg",
                    models.FloatField(blank=True, null=True, verbose_name="平均降水量"),
                ),
                (
                    "precipitation_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大降水量"),
                ),
                (
                    "precipitation_min",
                    models.FloatField(blank=True, null=True, verbose_name="最小降水量"),
                ),
                (
                    "precipitation_std",
                    models.FloatField(
                        blank=True, null=True, verbose_name="降水量标准差"
                    ),
                ),
                (
                    "humidity_avg",
                    models.FloatField(blank=True, null=True, verbose_name="平均湿度"),
                ),
                (
                    "humidity_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大湿度"),
                ),
                (
                    "humidity_min",
                    models.FloatField(blank=True, null=True, verbose_name="最小湿度"),
                ),
                (
                    "humidity_std",
                    models.FloatField(blank=True, null=True, verbose_name="湿度标准差"),
                ),
                (
                    "wind_speed_avg",
                    models.FloatField(blank=True, null=True, verbose_name="平均风速"),
                ),
                (
                    "wind_speed_max",
                    models.FloatField(blank=True, null=True, verbose_name="最大风速"),
                ),
                (
                    "wind_speed_min",
                    models.FloatField(blank=True, null=True, verbose_name="最小风速"),
                ),
                (
                    "wind_speed_std",
                    models.FloatField(blank=True, null=True, verbose_name="风速标准差"),
                ),
                ("chart_data", models.JSONField(default=dict, verbose_name="图表数据")),
                (
                    "report_file",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="climate_reports/",
                        verbose_name="分析报告",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "data_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="analysis_results",
                        to="environment.climatedatafile",
                        verbose_name="数据文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "气候分析结果",
                "verbose_name_plural": "气候分析结果",
                "db_table": "climate_analysis_results",
                "ordering": ["-created_at"],
            },
        ),
    ]
