# Generated by Django 5.2.4 on 2025-09-04 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0008_climatedatafile_climateanalysisresult"),
    ]

    operations = [
        migrations.AlterField(
            model_name="climatedatafile",
            name="file_type",
            field=models.CharField(
                choices=[("csv", "CSV"), ("xlsx", "Excel")],
                default="csv",
                max_length=10,
                verbose_name="文件类型",
            ),
        ),
    ]
