# Generated by Django 5.2.4 on 2025-09-04 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0009_alter_climatedatafile_file_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="processingtask",
            name="remote_sensing_image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="environment.remotesensingimage",
                verbose_name="遥感影像",
            ),
        ),
    ]
