# Generated by Django 5.2.4 on 2025-09-25 08:43

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0010_alter_processingtask_remote_sensing_image"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EcologicalIndexFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file",
                    models.FileField(
                        upload_to="ecological_indices/", verbose_name="文件"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "已上传"),
                            ("processing", "处理中"),
                            ("completed", "完成"),
                            ("failed", "失败"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "indices_data",
                    models.JSONField(default=dict, verbose_name="生态指数数据"),
                ),
                (
                    "timestamp",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="数据时间戳"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理完成时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "生态指数文件",
                "verbose_name_plural": "生态指数文件",
                "db_table": "ecological_index_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="EcologicalProjectFile",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("filename", models.CharField(max_length=255, verbose_name="文件名")),
                (
                    "file",
                    models.FileField(
                        upload_to="ecological_projects/", verbose_name="文件"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "已上传"),
                            ("processing", "处理中"),
                            ("completed", "完成"),
                            ("failed", "失败"),
                        ],
                        default="uploaded",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "geojson_data",
                    models.JSONField(default=dict, verbose_name="GeoJSON数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "processed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="处理完成时间"
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="上传用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "生态修复工程文件",
                "verbose_name_plural": "生态修复工程文件",
                "db_table": "ecological_project_files",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="OverlayAnalysisTask",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("name", models.CharField(max_length=255, verbose_name="分析任务名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="任务描述"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "等待中"),
                            ("processing", "处理中"),
                            ("completed", "已完成"),
                            ("failed", "失败"),
                            ("cancelled", "已取消"),
                        ],
                        default="pending",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                ("progress", models.IntegerField(default=0, verbose_name="进度百分比")),
                (
                    "current_step",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="当前步骤"
                    ),
                ),
                (
                    "analysis_results",
                    models.JSONField(default=dict, verbose_name="分析结果"),
                ),
                (
                    "overall_risk_level",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("low", "低风险"),
                            ("medium", "中风险"),
                            ("high", "高风险"),
                            ("critical", "极高风险"),
                        ],
                        max_length=20,
                        null=True,
                        verbose_name="总体风险等级",
                    ),
                ),
                (
                    "error_message",
                    models.TextField(blank=True, null=True, verbose_name="错误信息"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "started_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="开始时间"
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="完成时间"
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建用户",
                    ),
                ),
                (
                    "ecological_index_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="environment.ecologicalindexfile",
                        verbose_name="生态指数文件",
                    ),
                ),
                (
                    "ecological_project_file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="environment.ecologicalprojectfile",
                        verbose_name="生态修复工程文件",
                    ),
                ),
            ],
            options={
                "verbose_name": "叠加分析任务",
                "verbose_name_plural": "叠加分析任务",
                "db_table": "overlay_analysis_tasks",
                "ordering": ["-created_at"],
            },
        ),
    ]
