# Generated by Django 5.2.4 on 2025-10-31 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("environment", "0013_fix_choices_encoding"),
    ]

    operations = [
        migrations.AddField(
            model_name="overlayanalysistask",
            name="impact_raster_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="overlay_analysis/rasters/",
                verbose_name="影响强度栅格文件",
            ),
        ),
        migrations.AddField(
            model_name="overlayanalysistask",
            name="raster_layers_metadata",
            field=models.JSONField(default=dict, verbose_name="栅格图层元数据"),
        ),
        migrations.AddField(
            model_name="overlayanalysistask",
            name="risk_raster_file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="overlay_analysis/rasters/",
                verbose_name="风险等级栅格文件",
            ),
        ),
    ]
